%
% Name :
%   ray_test_firic.m
%
% Purpose :
%   Example of using raytrace_2d for a single ray which is trapped in
%   a duct and eventually becomes evanescent. Ionosphere generated by FIRIC.
%   This shows a weird pathalogical case probably caused by the use of 
%   Chapman layers to generate the ionospheric profiles. Chapman layers tend
%   to produce a deep valley between the E and F layers. 
%
% Calling sequence :
%   ray_test_firic
%
% Inputs :
%   None
%
% Outputs :
%   None
%
% Author:
%   V1.0  M.A. Cervera  16/04/2008
%     Initial Version
%
%   V1.1  M.A. Cervera  13/05/2008
%     Rays and ionosphere plotted on an arc to preserved curved Earth
%     geometry. 
%
%   V1.1a M.A. Cervera  20/11/2008
%      Updated comment block.
%
%   V1.2  M.A. Cervera  20/05/2016
%      Updated to use multi-threaded raytrace_2d
%


%
% setup general stuff
%
UT = [2001 6 15 9 30];        % UT - year, month, day, hour, minute
R12 = 137;                    % yearly smoothed sunspot number
kp = 3;                       % Kp index
speed_of_light = 2.99792458e8;

elev = 11;                   % ray elevation
ray_bear = 324.7;
origin_lat = -23.5;          % latitude of the start point of ray
origin_long = 133.7;;        % longitude of the start point of ray


%
% generate ionospheric, geomagnetic and irregularity grids
%
max_range = 4500;      % maximum range for sampling the ionosphere (km)
num_range = 501;        % number of ranges (must be < 2001)
range_inc = max_range ./ (num_range - 1);  % range cell size (km)

start_height = 0;      % start height for ionospheric grid (km)
height_inc = 0.5;         % height increment (km)
num_heights = 501;      % number of  heights (must be < 2001)

lat_ht_correction = 1;  % yes to low latitude ionospheric height correction

indices = [R12 0 0 0 kp];
[iono_pf_grid, iono_pf_grid_5, collision_freq, irreg] = ...
    gen_firic_grid_2d(origin_lat, origin_long, UT, indices, ray_bear, ...
                      max_range, num_range, range_inc, start_height, ...
		      height_inc, num_heights, 'firic', ...
		      lat_ht_correction);
		 
% convert plasma frequency grid to  electron density in electrons/cm^3
iono_en_grid = iono_pf_grid.^2 / 80.6164e-6;
iono_en_grid_5 = iono_pf_grid_5.^2 / 80.6164e-6;


%
% call raytrace
%
irregs_flag = 0;     % no irregularities
freq = 2.0;          % frequency (MHz)
nhops = 1;           % number of hops
tol = 1e-7;          % rkf tolerance

[ray_data, ray_path_data] = ...
    raytrace_2d(origin_lat, origin_long, elev, ray_bear, freq, nhops, ...
             tol, irregs_flag, iono_en_grid, iono_pf_grid_5, ...
	     collision_freq,start_height, height_inc, range_inc, irreg);
	 

%
% plot the ray and ionospheric slice on an arc
%
figure(1)

start_range = 0;
end_range = 4000;
end_range_idx = fix((end_range-start_range) ./ range_inc) + 1;
start_ht = start_height;
end_ht = 200;
eh_idx = end_ht ./ height_inc + 1;

iono_pf_subgrid = iono_pf_grid(1:eh_idx, 1:end_range_idx);
plot_ray_iono_slice(iono_pf_subgrid, start_range, end_range, range_inc, ...
    start_ht, end_ht, height_inc, ray_path_data, 'color', 'w', 'linewidth', 2);

set(gcf,'units','normal')
pos = get(gcf,'position');
pos(2) = 0.63;
set(gcf,'position', pos)

%
% zoom in on the ray where it becomes evanescent
%
figure(2)

start_range = 2900;
end_range = 4450;
sr_idx = fix(start_range ./ range_inc) + 1;
er_idx = fix(end_range ./ range_inc) + 1;
start_ht = 0;
end_ht = 200;
sh_idx = fix(start_ht ./ height_inc) + 1;
eh_idx = fix(end_ht ./ height_inc) + 1;

iono_pf_subgrid = iono_pf_grid(sh_idx:eh_idx, sr_idx:er_idx);
plot_ray_iono_slice(iono_pf_subgrid, start_range, end_range, range_inc, ...
    start_ht, end_ht, height_inc, ray_path_data, 'color', 'w', 'linewidth', 2);

set(gcf,'units','normal')
pos = get(gcf,'position');
pos(2) = 0.14;
set(gcf,'position', pos)
